### ISSUE TITLE
InternalOAuthError: failed to fetch user profile

### ISSUE THREAD

**Issue by satterly** [guardian/elk-stack#48]
On launching the stack the Kibana webpage responds with the following error:

```
InternalOAuthError: failed to fetch user profile (status: 403 data: {
"error": {
 "errors": [
  {
   "domain": "usageLimits",
   "reason": "accessNotConfigured",
   "message": "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration.",
   "extendedHelp": "https://console.developers.google.com"
  }
 ],
 "code": 403,
 "message": "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration."
}
}
)
   at /opt/logcabin/node_modules/passport-google-oauth/lib/passport-google-oauth/oauth2.js:88:28
   at passBackControl (/opt/logcabin/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/opt/logcabin/node_modules/passport-google-oauth/node_modules/passport-oauth/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:142:7)
   at IncomingMessage.EventEmitter.emit (events.js:117:20)
   at _stream_readable.js:920:16
   at process._tickCallback (node.js:415:13)
```

**Comment by satterly** [comment]
Make sure you have enabled the "Google+ API" for the same Project you used to create the OAuth2 credentials in the Google Developers Console.
